steps:
  - label: "Debug Environment"
    commands:
      - echo "Username is: $DOCKER_USERNAME"
      - echo "Password is: ${DOCKER_PASSWORD:0:4}****"  # only show partial for safety
    agents:
      queue: buildkite-queue
