steps:
  - label: "Debug environment"
    commands:
      - echo "DOCKER_USERNAME=$DOCKER_USERNAME"
      - echo "DOCKER_PASSWORD is set? ${DOCKER_PASSWORD:+yes}"
    agents:
      queue: buildkite-queue
