steps:
  - label: "Check environment variables"
    commands:
      - echo "DOCKER_USERNAME is: $DOCKER_USERNAME"
      - echo "DOCKER_PASSWORD is: ${DOCKER_PASSWORD:0:4}****"
    agents:
      queue: buildkite-queue
