steps:
  - label: "Build and Push Multiarch App"
    commands:
      - echo "Testing env hook..."
      - echo "DOCKER_USERNAME is: $DOCKER_USERNAME"  
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "Starting multiarch build as buildkite-agent user"
      - docker buildx rm mybuilder || true
      - docker buildx create --use --name mybuilder
      - docker buildx inspect --bootstrap
      - docker buildx build --platform linux/amd64,linux/arm64 \
          -t "$DOCKER_USERNAME/multi-arch-app:latest" \
          --push .  
    agents:
      queue: buildkite-queue1

