steps:
  - label: "Build and Push Python Microservice"
    commands: |
      export DOCKER_CONFIG=$HOME/.docker
      env | grep DOCKER_
      whoami
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker buildx use multiarch
      docker buildx inspect --bootstrap
      docker buildx build --platform linux/amd64,linux/arm64 \
        -t "$DOCKER_USERNAME/myapp:latest" \
        --push .
    agents:
      queue: buildkite-queue
