steps:
  - label: "Build and Push Python Microservice"
    commands: |
      echo "Checking DOCKER_USERNAME: $DOCKER_USERNAME"
      echo "Checking DOCKER_PASSWORD: $DOCKER_PASSWORD"
      docker buildx rm mybuilder || true
      docker buildx create --use --name mybuilder
      docker buildx inspect --bootstrap
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker buildx build --platform linux/amd64,linux/arm64 -t "$DOCKER_USERNAME/multi-arch-app:latest" --push .
    agents:
      queue: buildkite-queue
