steps:
  - label: "Debug Environment"
    commands:
      - echo "Buildkite-agent user: $(whoami)"
      - echo "DOCKER_USERNAME=$DOCKER_USERNAME"
      - echo "DOCKER_PASSWORD=${DOCKER_PASSWORD:+set}"
      - echo "DOCKER_CONFIG=$DOCKER_CONFIG"
    agents:
      queue: buildkite-queue
