steps:
  - label: "Build and Push Multiarch App"
    commands:
      - echo "Starting multiarch build as buildkite-agent user"
      - docker buildx rm mybuilder || true
      - docker buildx create --use --name mybuilder
      - sudo -u buildkite-agent docker buildx inspect --bootstrap
      - echo "DOCKER_USERNAME=$DOCKER_USERNAME"
      - docker build --platform linux/amd64 \
          -t "$DOCKER_USERNAME/multi-arch-app:latest" \
          --push .
    agents:
      queue: buildkite-queue
