steps:
  - label: "Build and Push Multiarch Python Image"
    commands:
      - docker buildx use multiarch
      - docker buildx inspect --bootstrap
      - docker buildx build --platform linux/amd64,linux/arm64 \
          -t "abhay900/myapp:latest" \
          --push .
    agents:
      queue: buildkite-queue
