steps:
  - label: "Build and Push Multiarch Python Image"
    commands:
      - docker buildx use multiarch
      - docker buildx inspect --bootstrap
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker buildx build --platform linux/amd64,linux/arm64 \
          -t "$DOCKER_USERNAME/myapp:latest" \
          --push .
    agents:
      queue: buildkite-queue
