steps:
  - label: "Build and Push Multiarch Image"
    commands:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker buildx use multiarch
      - docker buildx inspect --bootstrap
      - docker buildx build --platform linux/amd64,linux/arm64 \
          -t "$DOCKER_USERNAME/myimage:latest" \
          --push .
