steps:
  - label: "Debug Buildkite + Docker Env"
    commands:
      - echo "Buildkite agent user: $(whoami)"
      - echo "Home directory: $HOME"
      - echo "Docker environment variables:"
      - env | grep DOCKER_
      - echo "Docker info check:"
      - docker info | grep -E 'Username|UID|GID'
    agents:
      queue: buildkite-queue
