steps:
  - label: "Build and push multi-arch image"
    plugins:
      docker-login#v2.0.0:
        username: "${DOCKER_USERNAME}"
        password: "${DOCKER_PASSWORD}"
    commands:
      - docker buildx rm mybuilder || true
      - docker buildx create --use --name mybuilder
      - docker buildx inspect --bootstrap
      - docker buildx build --platform linux/amd64,linux/arm64 -t ${DOCKER_USERNAME}/multi-arch-app:latest --push .
    agents:
      queue: buildkite-queue
