steps:
  - label: "Debug Buildkite and Docker User"
    commands:
      - echo "Checking the Buildkite and Docker environment..."
      - echo "Buildkite Agent User:"
      - whoami
      - id
      - echo "HOME: $HOME"
      - echo "Docker Environment Variables:"
      - env | grep DOCKER_
      - echo "Docker Info (Docker username, UID, GID):"
      - docker info | grep -E 'Username|Root|UID|GID'
    agents:
      queue: buildkite-queue
