env:
  DOCKER_USERNAME: "abhay900"
  DOCKER_PASSWORD: "dckr_pat_4lwatfEFAPcN3davjQ2aSVZLU74"

steps:
  - label: "Build and push multi-arch image"
    commands:
      - docker buildx rm mybuilder || true
      - docker buildx create --use --name mybuilder
      - docker buildx inspect --bootstrap
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker buildx build --platform linux/amd64,linux/arm64 -t ${DOCKER_USERNAME}/multi-arch-app:latest --push .
    agents:
      queue: buildkite-queue
