steps:
  - label: "Build and Push Python Microservice"
    commands: |
      docker buildx rm mybuilder || true
      docker buildx create --use --name mybuilder
      docker buildx inspect --bootstrap
      echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin      
      docker buildx build --platform linux/amd64,linux/arm64 -t "$DOCKER_USERNAME/multi-arch-app:latest" --push .
    agents:
      queue: buildkite-queue
